query PaginatedRecipes($page: Int, $perPage: Int) {
  paginatedRecipes(page: $page, perPage: $perPage) {
    data {
      cookingTime
      prepTime
      parts {
        name
        ingredients {
          id
          extraInfo
          ingredientText
          quantity
          maxQuantity
          minQuantity
          unit
          unitText
        }
      }
      categories {
        name
      }
      ingredients {
        id
        extraInfo
        ingredientText
        quantity
        maxQuantity
        minQuantity
        unit
        unitText
      }
      images {
        altText
        url
      }
      tags {
        name
      }
      description
      id
      seasons {
        id
        name

      }
      instructions {
        content
        listIndex
        order
        type
      }
      servingsMax
      servingsMin
      servingsText
      sourceUrl
      title
    }
    meta {
      lastPage
      total
      currentPage
    }
  }
}
