version: '3.7'
services:
  postgres-nutri:
    container_name: postgres-nutri
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: "--wal-segsize=512"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./deploy/docker-compose/postgres-nutri:/docker-entrypoint-initdb.d
      - pgdata-postgres-nutri:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  csvkit-importer:
    build:
      context: ./deploy/docker-compose/csvkit-importer
      dockerfile: Dockerfile.csvkit
    environment:
      POSTGRES_HOST: postgres-nutri
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./deploy/docker-compose/csvkit-importer/data:/data
      - ./deploy/docker-compose/csvkit-importer/config:/config
      - ./deploy/docker-compose/csvkit-importer/import_script.py:/import_script.py
    command: python /import_script.py
    depends_on:
      postgres-nutri:
        condition: service_healthy

  # Used for access to local EMAIL notification functionality
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  pgdata-postgres-nutri:
