import { cva } from 'class-variance-authority';

export const iconVariant = cva('', {
  variants: {
    size: {
      xxs: [],
      xs: [],
      sm: [],
      md: [],
      lg: [],
    },
    variant: {
      solid: [],
      outline: [],
      link: [],
      ghost: [],
    },
    colorScheme: {
      primary: [],
      gray: [],
      blue: [],
      warning: [],
      error: [],
    },
  },
  compoundVariants: [
    // xxs size variants
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'blue',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'warning',
      className: ['w-3 h-3', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-3 h-3', 'text-white'],
    },
    // Repeat for other sizes (xs, sm, md, lg) and variants (outline, link, ghost)
    // ...
  ],
});

export const linkButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-primary-700',
          'hover:text-primary-800',
          'focus:text-primary-800',
          'hover:underline',
          'focus:underline',
        ],
        gray: [
          'text-gray-700',
          'hover:text-gray-800',
          'focus:text-gray-800',
          'hover:underline',
          'focus:underline',
        ],
        blue: [
          'text-blue-700',
          'hover:text-blue-800',
          'focus:text-blue-800',
          'hover:underline',
          'focus:underline',
        ],
        warning: [
          'text-warning-700',
          'hover:text-warning-800',
          'focus:text-warning-800',
          'hover:underline',
          'focus:underline',
        ],
        error: [
          'text-error-700',
          'hover:text-error-800',
          'focus:text-error-800',
          'hover:underline',
          'focus:underline',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const solidButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'text-white',
          'border',
          'border-solid',
          'bg-primary-600',
          'hover:bg-primary-700',
          'focus:bg-primary-700',
          'border-primary-600',
          'hover:border-primary-700',
          'focus:ring-2',
          'focus:ring-primary-200',
        ],
        gray: [
          'text-white',
          'border',
          'border-solid',
          'bg-gray-600',
          'hover:bg-gray-700',
          'focus:bg-gray-700',
          'border-gray-600',
          'hover:border-gray-700',
          'focus:ring-2',
          'focus:ring-gray-200',
        ],
        blue: [
          'text-white',
          'border',
          'border-solid',
          'bg-blue-600',
          'hover:bg-blue-700',
          'focus:bg-blue-700',
          'border-blue-600',
          'hover:border-blue-700',
          'focus:ring-2',
          'focus:ring-blue-200',
        ],
        lavender: [
          'text-white',
          'border',
          'border-solid',
          'bg-lavender-600',
          'hover:bg-lavender-700',
          'focus:bg-lavender-700',
          'border-lavender-600',
          'hover:border-lavender-700',
          'focus:ring-2',
          'focus:ring-lavender-200',
        ],
        warning: [
          'text-white',
          'border',
          'border-solid',
          'bg-warning-600',
          'hover:bg-warning-700',
          'focus:bg-warning-700',
          'border-warning-600',
          'hover:border-warning-700',
          'focus:ring-2',
          'focus:ring-warning-200',
        ],
        error: [
          'text-white',
          'border',
          'border-solid',
          'bg-error-600',
          'hover:bg-error-700',
          'focus:bg-error-700',
          'border-error-600',
          'hover:border-error-700',
          'focus:ring-2',
          'focus:ring-error-200',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const ghostButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-transparent',
          'text-primary-600',
          'shadow-none',
          'hover:text-primary-700',
          'focus:text-primary-700',
          'hover:bg-primary-50',
          'focus:bg-primary-50',
        ],
        gray: [
          'bg-transparent',
          'shadow-none',
          'text-gray-600',
          'hover:text-gray-700',
          'focus:text-gray-700',
          'hover:bg-gray-50',
          'focus:bg-gray-50',
        ],
        blue: [
          'bg-transparent',
          'text-blue-600',
          'shadow-none',
          'hover:text-blue-700',
          'focus:text-blue-700',
          'hover:bg-blue-50',
          'focus:bg-blue-50',
        ],
        lavender: [
          'bg-transparent',
          'text-lavender-600',
          'shadow-none',
          'hover:text-lavender-700',
          'focus:text-lavender-700',
          'hover:bg-lavender-50',
          'focus:bg-lavender-50',
        ],

        warning: [
          'bg-transparent',
          'text-warning-600',
          'shadow-none',
          'hover:text-warning-700',
          'focus:text-warning-700',
          'hover:bg-warning-50',
          'focus:bg-warning-50',
        ],
        error: [
          'bg-transparent',
          'text-error-600',
          'shadow-none',
          'hover:text-error-700',
          'focus:text-error-700',
          'hover:bg-error-50',
          'focus:bg-error-50',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);

export const outlineButton = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'whitespace-nowrap',
    'gap-2',
    'text-base',
    'font-semibold',
    'shadow-xs',
    'outline-none',
    'transition',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
  ],
  {
    variants: {
      colorScheme: {
        primary: [
          'bg-primary-50',
          'text-primary-700',
          'border',
          'border-solid',
          'border-primary-300',
          'hover:bg-primary-100',
          'hover:text-primary-800',
          'focus:bg-primary-100',
        ],
        gray: [
          'bg-gray-50',
          'text-gray-700',
          'border',
          'border-solid',
          'border-gray-300',
          'hover:bg-gray-100',
          'hover:text-gray-800',
          'focus:bg-gray-100',
        ],
        blue: [
          'bg-blue-50',
          'text-blue-700',
          'border',
          'border-solid',
          'border-blue-300',
          'hover:bg-blue-100',
          'hover:text-blue-800',
          'focus:bg-blue-100',
        ],
        lavender: [
          'bg-lavender-50',
          'text-lavender-700',
          'border',
          'border-solid',
          'border-lavender-300',
          'hover:bg-lavender-100',
          'hover:text-lavender-800',
          'focus:bg-lavender-100',
        ],

        warning: [
          'bg-warning-50',
          'text-warning-700',
          'border',
          'border-solid',
          'border-warning-300',
          'hover:bg-warning-100',
          'hover:text-warning-800',
          'focus:bg-warning-100',
        ],
        error: [
          'bg-error-50',
          'text-error-700',
          'border',
          'border-solid',
          'border-error-300',
          'hover:bg-error-100',
          'hover:text-error-800',
          'focus:bg-error-100',
        ],
      },
    },
    defaultVariants: {
      colorScheme: 'gray',
    },
  },
);
