query PaginatedFoods($page: Int, $perPage: Int, $sortInput: FoodOrderByWithRelationInput, $filterInput: FoodWhereInput) {
  paginatedFoods(page: $page, perPage: $perPage, sortInput: $sortInput, filterInput: $filterInput) {
    data {
      id
      updatedAt
      sourceId
      scientificName
      description
      categories {
        category {
          description
          code
        }
      }
      nutrients {
        amount
        confidenceCode
        id
        max
        median
        min
        nutrient {
          id
          name
          unitName
          foodNutrients {
            amount
            max
            median
            min
            confidenceCode
          }
        }
      }
      portions {
        amount
        gramWeight
        measureUnit {
          name
        }
        measureUnitName
        portionDescription
      }
      brandedFood {
        brandOwner
        gtinUpc
        nutritionLabel {
          brandedFoodId
          calories
          totalFat
          saturatedFat
          transFat
          cholesterol
          sodium
          totalCarbohydrate
          dietaryFiber
          totalSugars
          addedSugars
          protein
          vitaminA
          vitaminC
          vitaminD
          calcium
          iron
          potassium
          servingsPerContainer
          householdServingFullText

        }
      }
    }
  }
}
