#!/bin/bash

# Purpose:
# This script is designed to automate the creation of PostgreSQL roles based on usernames extracted from SQL dump files.
# These SQL files are generated from an AWS RDS database environment via pg_dump & connection established using a boundary client. The boundary client
# creates usernames with varying names, often including unique tokens or identifiers within the usernames. This script
# processes each SQL file located in the same directory as the script, searching for GRANT USAGE statements to identify
# usernames. It then creates a PostgreSQL role for each unique username found, ensuring no duplicates are created.
# Usernames extracted from the SQL files may be enclosed in quotes; this script handles such cases by removing the
# quotes before attempting to create roles. This ensures compatibility with usernames generated by the boundary client,
# which may include special characters or be encapsulated in quotes.
# It also includes cache mechanism to store the create role commands in a file for future runs so it is done faster.


# WHEN USING IN ANOTHER REPO CHANGE THIS TO THE CORRECT USERNAME, should match the one used in dump command
PSQL_USERNAME_OWNER="nutri"

# Directory containing the script and SQL files
SCRIPT_DIR="$(dirname "$0")"

# Use a temporary file to track which usernames have been processed
PROCESSED_USERS_FILE=$(mktemp)
# create command list
CREATE_ROLE_COMMANDS=()

create_role_for_username() {
    local username="$1"
    local store_in_cache="$2"
    username=$(echo "$username" | sed 's/^"//;s/"$//')

    echo "creating role for username: $username"

    # Check if the username has already been processed
    if ! grep -q "^${username}$" "$PROCESSED_USERS_FILE"; then
        local command="CREATE ROLE \"${username}\" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD NULL;"

        if [ "$store_in_cache" = "true" ]; then
            CREATE_ROLE_COMMANDS+=("$command")
        fi
        # Execute the role creation command
        psql -v ON_ERROR_STOP=1 --username "$PSQL_USERNAME_OWNER" -c "$command"
        # Mark this username as processed
        echo "$username" >> "$PROCESSED_USERS_FILE"
    else
      echo "Role already exists for username: $username"
    fi
}

create_role_for_username "postgres" "false"

while read -r sql_file; do
    cache_file="${sql_file}.cache"
    if [ -f "$cache_file" ]; then
        echo "Processing $cache_file"
        psql -v ON_ERROR_STOP=1 --username "$PSQL_USERNAME_OWNER" -f "$cache_file"
    else
        echo "Processing $sql_file to set dynamic roles"
        while read -r username; do
            create_role_for_username "$username" "true"
        done < <(grep -oP "GRANT USAGE ON SCHEMA public TO \K[^;]+" "$sql_file")

        # Store command list in cache file
        echo "Store command list in cache file for future runs. $cache_file"
        # Iterate over the array and append each element to the file
        for command in "${CREATE_ROLE_COMMANDS[@]}"; do
            echo "Storing following command in cache: $command"
            echo "$command" >> "$cache_file"
        done
    fi
done < <(find "$SCRIPT_DIR" -maxdepth 1 -type f -name '*.sql')

rm "$PROCESSED_USERS_FILE"
