import { registerEnumType } from '@nestjs/graphql';

export enum ColumnViewTypeEnum {
  MATCHES_CREATED_AT = 'MATCHES_CREATED_AT',
  MATCHES_UPDATED_AT = 'MATCHES_UPDATED_AT',
  MATCHES_INGREDIENT_TEXT = 'MATCHES_INGREDIENT_TEXT',
  MATCHES_STATUS = 'MATCHES_STATUS',
  MATCHES_SELECTED_FOOD_MATCH_ID = 'MATCHES_SELECTED_FOOD_MATCH_ID',
  MATCHES_ACTIONS = 'MATCHES_ACTIONS',

  RECIPES_DESCRIPTION = 'RECIPES_DESCRIPTION',
  RECIPES_COOKING_TIME = 'RECIPES_COOKING_TIME',
  RECIPES_PREP_TIME = 'RECIPES_PREP_TIME',
  RECIPES_SERVINGS_MAX = 'RECIPES_SERVINGS_MAX',
  RECIPES_SERVINGS_MIN = 'RECIPES_SERVINGS_MIN',
  RECIPES_SERVINGS_TEXT = 'RECIPES_SERVINGS_TEXT',
  RECIPES_SOURCE_URL = 'RECIPES_SOURCE_URL',
  RECIPES_TITLE = 'RECIPES_TITLE',
  RECIPES_CREATED_AT = 'RECIPES_CREATED_AT',
  RECIPES_UPDATED_AT = 'RECIPES_UPDATED_AT',

  PATIENTS_NAME = 'PATIENTS_NAME',
  PATIENTS_AGE = 'PATIENTS_AGE',
  PATIENTS_HEIGHT = 'PATIENTS_HEIGHT',
  PATIENTS_WEIGHT = 'PATIENTS_WEIGHT',
  PATIENTS_BMI = 'PATIENTS_BMI',
  PATIENTS_FITNESS_LEVEL = 'PATIENTS_FITNESS_LEVEL',
  PATIENTS_DIETARY_PREFERENCES = 'PATIENTS_DIETARY_PREFERENCES',
  PATIENTS_DIETARY_RESTRICTIONS = 'PATIENTS_DIETARY_RESTRICTIONS',
  PATIENTS_HEALTH_PROBLEMS = 'PATIENTS_HEALTH_PROBLEMS',
  PATIENTS_ALLERGIES = 'PATIENTS_ALLERGIES',

  POLLS_NAME = 'POLLS_NAME',
  POLLS_TAGS = 'POLLS_TAGS',
  POLLS_QUESTION_COUNT = 'POLLS_QUESTION_COUNT',
  POLLS_CREATED_DATE = 'POLLS_CREATED_DATE',
  POLLS_LAST_MODIFIED_DATE = 'POLLS_LAST_MODIFIED_DATE',
  POLLS_AUTHOR = 'POLLS_AUTHOR',
  POLLS_STATUS = 'POLLS_STATUS',
  POLLS_USED_COUNT = 'POLLS_USED_COUNT',
}

registerEnumType(ColumnViewTypeEnum, {
  name: 'ColumnViewType',
});
