import { registerEnumType } from "@nestjs/graphql";

export enum TableIdTypeEnum {
  MANUAL_REVIEWS_MATCHES = "MANUAL_REVIEWS_MATCHES",
  MANUAL_REVIEWS_FOOD_MATCHES = "MANUAL_REVIEWS_FOOD_MATCHES",
  POLLS = "POLLS",
  RECIPES = "RECIPES",
  FAVORITE_RECIPES = 'FAVORITE_RECIPES',
  RECENTLY_ADDED_RECIPES = 'RECENTLY_ADDED_RECIPES',
  PATIENTS = 'PATIENTS',
  INGREDIENTS = 'INGREDIENTS',
  SHOPPING_LISTS = 'SHOPPING_LISTS',
  MEAL_PLANS = 'MEAL_PLANS',
}
registerEnumType(TableIdTypeEnum, {
  name: 'TableIdType',
});
