import {Patient} from "./type";

export const dummyPatients: Patient[] = [
  {
    id: '1b',
    name: 'John Doe',
    age: 35,
    height: 180,
    weight: 80,
    bmi: 24.7,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Low-carb', 'High-protein'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: ['Hypertension'],
    allergies: ['Peanuts']
  },
  {
    id: '2b',
    name: 'Jane Smith',
    age: 28,
    height: 165,
    weight: 60,
    bmi: 22.0,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegetarian'],
    dietaryRestrictions: ['Lactose-free'],
    diagnosedHealthProblems: [],
    allergies: ['Shellfish']
  },
  {
    id: '3b',
    name: 'Bob Johnson',
    age: 52,
    height: 175,
    weight: 90,
    bmi: 29.4,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Type 2 Diabetes', 'High Cholesterol'],
    allergies: []
  },
  {
    id: '4b',
    name: 'Alice Brown',
    age: 41,
    height: 170,
    weight: 65,
    bmi: 22.5,
    fitnessLevel: 'EXTRA_ACTIVE',
    dietaryPreferences: ['Paleo'],
    dietaryRestrictions: [],
    diagnosedHealthProblems: [],
    allergies: ['Soy']
  },
  {
    id: '5b',
    name: 'Charlie Wilson',
    age: 60,
    height: 178,
    weight: 85,
    bmi: 26.8,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Low-fat'],
    dietaryRestrictions: ['Low-sugar'],
    diagnosedHealthProblems: ['Osteoarthritis'],
    allergies: ['Eggs', 'Tree nuts']
  },
  {
    id: 'a1',
    name: 'John Doe',
    age: 35,
    height: 180,
    weight: 80,
    bmi: 24.7,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Low-carb', 'High-protein'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: ['Hypertension'],
    allergies: ['Peanuts']
  },
  {
    id: 'a2',
    name: 'Jane Smith',
    age: 28,
    height: 165,
    weight: 60,
    bmi: 22.0,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegetarian'],
    dietaryRestrictions: ['Lactose-free'],
    diagnosedHealthProblems: [],
    allergies: ['Shellfish']
  },
  {
    id: 'a3',
    name: 'Bob Johnson',
    age: 52,
    height: 175,
    weight: 90,
    bmi: 29.4,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Type 2 Diabetes', 'High Cholesterol'],
    allergies: []
  },
  {
    id: '4a',
    name: 'Alice Brown',
    age: 41,
    height: 170,
    weight: 65,
    bmi: 22.5,
    fitnessLevel: 'EXTRA_ACTIVE',
    dietaryPreferences: ['Paleo'],
    dietaryRestrictions: [],
    diagnosedHealthProblems: [],
    allergies: ['Soy']
  },
  {
    id: '5',
    name: 'Charlie Wilson',
    age: 60,
    height: 178,
    weight: 85,
    bmi: 26.8,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Low-fat'],
    dietaryRestrictions: ['Low-sugar'],
    diagnosedHealthProblems: ['Osteoarthritis'],
    allergies: ['Eggs', 'Tree nuts']
  },
  {
    id: '6',
    name: 'Sarah Davis',
    age: 33,
    height: 163,
    weight: 72,
    bmi: 27.1,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Low-carb', 'Keto'],
    dietaryRestrictions: ['Dairy-free'],
    diagnosedHealthProblems: ['PCOS'],
    allergies: ['Latex']
  },
  {
    id: '7',
    name: 'Michael Thompson',
    age: 45,
    height: 182,
    weight: 95,
    bmi: 28.7,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Pescatarian'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Hypertension', 'High Cholesterol'],
    allergies: ['Shellfish']
  },
  {
    id: '8',
    name: 'Emily Miller',
    age: 29,
    height: 168,
    weight: 62,
    bmi: 22.0,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegan'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: [],
    allergies: ['Peanuts', 'Tree nuts']
  },
  {
    id: '9',
    name: 'David Lee',
    age: 54,
    height: 175,
    weight: 82,
    bmi: 26.8,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-carb'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Type 2 Diabetes'],
    allergies: ['Eggs']
  },
  {
    id: '10',
    name: 'Olivia Anderson',
    age: 39,
    height: 163,
    weight: 58,
    bmi: 21.8,
    fitnessLevel: 'EXTRA_ACTIVE',
    dietaryPreferences: ['Paleo', 'High-protein'],
    dietaryRestrictions: [],
    diagnosedHealthProblems: ['Hypothyroidism'],
    allergies: ['Soy']
  },
  {
    id: '11',
    name: 'William Davis',
    age: 47,
    height: 180,
    weight: 88,
    bmi: 27.2,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-fat'],
    dietaryRestrictions: ['Low-sugar'],
    diagnosedHealthProblems: ['High Cholesterol'],
    allergies: ['Tree nuts']
  },
  {
    id: '12',
    name: 'Isabella Garcia',
    age: 25,
    height: 165,
    weight: 54,
    bmi: 19.8,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegetarian', 'High-protein'],
    dietaryRestrictions: ['Lactose-free'],
    diagnosedHealthProblems: [],
    allergies: ['Shellfish']
  },
  {
    id: '13',
    name: 'Alexander Hernandez',
    age: 58,
    height: 172,
    weight: 92,
    bmi: 31.1,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Low-carb', 'Mediterranean'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Hypertension', 'Type 2 Diabetes'],
    allergies: ['Peanuts']
  },
  {
    id: '14',
    name: 'Sofia Morales',
    age: 32,
    height: 160,
    weight: 67,
    bmi: 26.2,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Paleo', 'Low-fat'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: ['PCOS'],
    allergies: ['Soy']
  },
  {
    id: '15',
    name: 'Daniel Ramirez',
    age: 41,
    height: 178,
    weight: 85,
    bmi: 26.8,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-carb'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['High Cholesterol'],
    allergies: ['Shellfish']
  },
  {
    id: '16',
    name: 'Mia Sanchez',
    age: 27,
    height: 163,
    weight: 59,
    bmi: 22.2,
    fitnessLevel: 'EXTRA_ACTIVE',
    dietaryPreferences: ['Vegan', 'High-protein'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: [],
    allergies: ['Peanuts', 'Tree nuts']
  },
  {
    id: '17',
    name: 'Jacob Flores',
    age: 51,
    height: 175,
    weight: 92,
    bmi: 30.0,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Mediterranean', 'Low-fat'],
    dietaryRestrictions: ['Low-sugar'],
    diagnosedHealthProblems: ['Type 2 Diabetes', 'Hypertension'],
    allergies: ['Eggs']
  },
  {
    id: '18',
    name: 'Abigail Reyes',
    age: 35,
    height: 168,
    weight: 63,
    bmi: 22.3,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Paleo', 'High-protein'],
    dietaryRestrictions: ['Dairy-free'],
    diagnosedHealthProblems: ['Hypothyroidism'],
    allergies: ['Soy']
  },
  {
    id: '19',
    name: 'Ethan Gutierrez',
    age: 44,
    height: 182,
    weight: 90,
    bmi: 27.2,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-carb'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Hypertension'],
    allergies: ['Tree nuts']
  },
  {
    id: '20',
    name: 'Isabella Diaz',
    age: 31,
    height: 162,
    weight: 55,
    bmi: 20.9,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegetarian', 'High-protein'],
    dietaryRestrictions: ['Lactose-free'],
    diagnosedHealthProblems: [],
    allergies: ['Shellfish']
  },
  {
    id: '21',
    name: 'Lucas Castillo',
    age: 62,
    height: 175,
    weight: 88,
    bmi: 28.7,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Mediterranean', 'Low-fat'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Osteoarthritis', 'High Cholesterol'],
    allergies: ['Peanuts']
  },
  {
    id: '22',
    name: 'Sophia Ramos',
    age: 29,
    height: 163,
    weight: 61,
    bmi: 22.9,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Paleo', 'Low-carb'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: ['PCOS'],
    allergies: ['Soy']
  },
  {
    id: '23',
    name: 'Noah Mendoza',
    age: 48,
    height: 180,
    weight: 92,
    bmi: 28.4,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-carb'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Type 2 Diabetes', 'Hypertension'],
    allergies: ['Shellfish']
  },
  {
    id: '24',
    name: 'Emma Ortiz',
    age: 36,
    height: 165,
    weight: 64,
    bmi: 23.5,
    fitnessLevel: 'EXTRA_ACTIVE',
    dietaryPreferences: ['Vegan', 'High-protein'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: [],
    allergies: ['Peanuts', 'Tree nuts']
  },
  {
    id: '25',
    name: 'Liam Dominguez',
    age: 55,
    height: 178,
    weight: 95,
    bmi: 30.0,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Mediterranean', 'Low-fat'],
    dietaryRestrictions: ['Low-sugar'],
    diagnosedHealthProblems: ['Type 2 Diabetes', 'Osteoarthritis'],
    allergies: ['Eggs']
  },
  {
    id: '26',
    name: 'Isabella Alvarado',
    age: 38,
    height: 170,
    weight: 68,
    bmi: 23.5,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Paleo', 'High-protein'],
    dietaryRestrictions: ['Dairy-free'],
    diagnosedHealthProblems: ['Hypothyroidism'],
    allergies: ['Soy']
  },
  {
    id: '27',
    name: 'Ethan Moreno',
    age: 42,
    height: 185,
    weight: 88,
    bmi: 25.7,
    fitnessLevel: 'LIGHT_ACTIVE',
    dietaryPreferences: ['Mediterranean', 'Low-carb'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['High Cholesterol'],
    allergies: ['Tree nuts']
  },
  {
    id: '28',
    name: 'Mia Vargas',
    age: 26,
    height: 160,
    weight: 53,
    bmi: 20.7,
    fitnessLevel: 'VERY_ACTIVE',
    dietaryPreferences: ['Vegetarian', 'High-protein'],
    dietaryRestrictions: ['Lactose-free'],
    diagnosedHealthProblems: [],
    allergies: ['Shellfish']
  },
  {
    id: '29',
    name: 'Lucas Soto',
    age: 59,
    height: 172,
    weight: 85,
    bmi: 28.7,
    fitnessLevel: 'SEDENTARY',
    dietaryPreferences: ['Mediterranean', 'Low-fat'],
    dietaryRestrictions: ['Low-sodium'],
    diagnosedHealthProblems: ['Hypertension', 'High Cholesterol'],
    allergies: ['Peanuts']
  },
  {
    id: '30',
    name: 'Sophia Gomez',
    age: 34,
    height: 165,
    weight: 59,
    bmi: 21.7,
    fitnessLevel: 'MODERATELY_ACTIVE',
    dietaryPreferences: ['Paleo', 'Low-carb'],
    dietaryRestrictions: ['Gluten-free'],
    diagnosedHealthProblems: ['PCOS'],
    allergies: ['Soy']
  },
];
