export enum IngredientMatchingErrorCode {
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
  INVALID_STATUS = 'INVALID_STATUS',
  FOOD_NOT_FOUND = 'FOOD_NOT_FOUND',
  CROSS_ENCODING_FAILED = 'CROSS_ENCODING_FAILED',
  NO_VALID_MATCHES = 'NO_VALID_MATCHES',
  NO_CANDIDATES = 'NO_CANDIDATES',
}
